AZURE_LOCATION: 'eastus'
RESOURCE_NAME_PREFIX: 'az-apimlz01'
ENVIRONMENT_TAG: 'production'
DEPLOYMENT_NAME: 'apim-demo-deployment'
VM_USERNAME: 'agent'
ACCOUNT_NAME: 'repalce me in repo secrets'
CICD_AGENT_TYPE: 'azuredevops'
CERT_TYPE: 'selfsigned'
