AZURE_LOCATION: 'eastus2'
RESOURCE_NAME_PREFIX: 'rjmalz82'
ENVIRONMENT_TAG: 'dev'
DEPLOYMENT_NAME: 'ase-demo-deployment'
VM_USERNAME: 'rjmdemo'
ACCOUNT_NAME: ${{secrets.ACCOUNT_NAME}}
CICD_AGENT_TYPE: 'none'
CERT_TYPE: 'selfsigned'
